#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#define PREVENT_STUCK_MODIFIERS
#define RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHE_CENTER
#define RGBLIGHT_EFFECT_BREATHE_CENTER 1.85
#undef RGBLIGHT_EFFECT_BREATHE_MAX
#define RGBLIGHT_EFFECT_BREATHE_MAX 200
#undef RGBLIGHT_EFFECT_SNAKE_LENGTH
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 1    // How many LEDs wide to light up
#endif
